# To predict : cnt i.e; count of total rental bikes including both casual and registered

In [48]:
# importing the necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [50]:
# Loading the dataset and viewing the first five rows of the dataset
df = pd.read_csv(r"D:\python folders\datasets\bike+sharing+dataset\day.csv")
df.head()

instant      dteday  season  yr  mnth  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1        0        6           0   
1        2  2011-01-02       1   0     1        0        0           0   
2        3  2011-01-03       1   0     1        0        1           1   
3        4  2011-01-04       1   0     1        0        2           1   
4        5  2011-01-05       1   0     1        0        3           1   

   weathersit      temp     atemp       hum  windspeed  casual  registered  \
0           2  0.344167  0.363625  0.805833   0.160446     331         654   
1           2  0.363478  0.353739  0.696087   0.248539     131         670   
2           1  0.196364  0.189405  0.437273   0.248309     120        1229   
3           1  0.200000  0.212122  0.590435   0.160296     108        1454   
4           1  0.226957  0.229270  0.436957   0.186900      82        1518   

    cnt  
0   985  
1   801  
2  1349  
3  1562  
4  1600

In [70]:
# checking for the number of unique values in all columns of the loaded datset
df.nunique()

instant       731
dteday        731
season          4
yr              2
mnth           12
holiday         2
weekday         7
workingday      2
weathersit      3
temp          499
atemp         690
hum           595
windspeed     650
casual        606
registered    679
cnt           696
dtype: int64

In [4]:
#checking unique values in each column separately 
df.season.unique()

array([1, 2, 3, 4], dtype=int64)

In [5]:
df.yr.unique()

array([0, 1], dtype=int64)

In [6]:
df.mnth.unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int64)

In [7]:
df.holiday.unique()

array([0, 1], dtype=int64)

In [8]:
df.weekday.unique()

array([6, 0, 1, 2, 3, 4, 5], dtype=int64)

In [9]:
df.workingday.unique()

array([0, 1], dtype=int64)

In [10]:
df.weathersit.unique()

array([2, 1, 3], dtype=int64)

In [71]:
# checking for the null values and the total number of null values in every column
df.isnull().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

In [56]:
# checking for string/object columns
df.select_dtypes(include='object').columns.to_list()

['dteday']

In [72]:
#creating the feature set
X= df.drop(['dteday','cnt'], axis=1)
X.head()

instant  season  yr  mnth  holiday  weekday  workingday  weathersit  \
0        1       1   0     1        0        6           0           2   
1        2       1   0     1        0        0           0           2   
2        3       1   0     1        0        1           1           1   
3        4       1   0     1        0        2           1           1   
4        5       1   0     1        0        3           1           1   

       temp     atemp       hum  windspeed  casual  registered  
0  0.344167  0.363625  0.805833   0.160446     331         654  
1  0.363478  0.353739  0.696087   0.248539     131         670  
2  0.196364  0.189405  0.437273   0.248309     120        1229  
3  0.200000  0.212122  0.590435   0.160296     108        1454  
4  0.226957  0.229270  0.436957   0.186900      82        1518

In [73]:
# creating the target/dependent set
y = df[['cnt']]
y.head()

cnt
0   985
1   801
2  1349
3  1562
4  1600

In [74]:
# importing linear regression from linear model class
from sklearn.linear_model import LinearRegression

In [61]:
# importing train test split from model selection class of sklearn
from sklearn.model_selection import train_test_split

In [62]:
X_train, X_test, y_train, y_test = train_test_split(X,y , test_size=0.3, random_state=33)
# fitting the training data to the model
linreg = LinearRegression()
linreg.fit(X_train, y_train)

LinearRegression()

In [65]:
# making predictions on test set 
y_pred = linreg.predict(X_test)
y_pred[170:]

array([[6234.],
       [4708.],
       [5102.],
       [4579.],
       [4459.],
       [1011.],
       [4785.],
       [4714.],
       [1872.],
       [6664.],
       [3717.],
       [5629.],
       [3606.],
       [4339.],
       [3944.],
       [6073.],
       [5499.],
       [3910.],
       [8555.],
       [6591.],
       [4367.],
       [6772.],
       [6398.],
       [6917.],
       [7040.],
       [4991.],
       [5668.],
       [7384.],
       [7907.],
       [5323.],
       [1000.],
       [5342.],
       [5267.],
       [5345.],
       [7105.],
       [3389.],
       [2425.],
       [3126.],
       [3873.],
       [3959.],
       [1749.],
       [1317.],
       [4040.],
       [4511.],
       [4639.],
       [2493.],
       [2133.],
       [7466.],
       [4332.],
       [7216.]])

In [75]:
# importing mean_squared_error and r2_score from the metrics class to evaluate model performance 

from sklearn.metrics import mean_squared_error, r2_score
print('mean squared error: ', mean_squared_error(y_pred, y_test))
print()
print('r2 score : ', r2_score(y_pred,y_test))
print()
print('root mean squared error: ', np.sqrt(mean_squared_error(y_pred, y_test)))

mean squared error:  1.7842103692037348e-24

r2 score :  1.0

root mean squared error:  1.335743377001636e-12


In [67]:
linreg.predict(X[650:655])

array([[7282.],
       [7109.],
       [6639.],
       [5875.],
       [7534.]])

In [68]:
y[650:655]

cnt
650  7282
651  7109
652  6639
653  5875
654  7534